if (MATAR_ENABLE_KOKKOS)
    add_executable(matVec matVec.cpp)
    add_executable(powerIter powerIter.cpp)
    add_executable(spPower sparsePowerIter.cpp)
    add_executable(spatVec sparseMatVec.cpp)

    target_link_libraries(spatVec ${LINKING_LIBRARIES})
    target_link_libraries(matVec ${LINKING_LIBRARIES})
    target_link_libraries(powerIter ${LINKING_LIBRARIES})
    target_link_libraries(spPower ${LINKING_LIBRARIES})
endif()
