#include "matar.h"
#include "gtest/gtest.h"
#include <stdio.h>

using namespace mtr; // matar namespace

namespace {
// All FOR_ALL kernels in this file set every row stride to the same maximum
// column count.  Extracting them to a free function keeps KOKKOS_LAMBDA out of
// the private TestBody() generated by TEST_F(), which nvcc cannot compile.
inline void set_all_strides(DDynamicRaggedRightArrayKokkos<double>& array,
                             size_t n_rows, size_t n_cols) {
    FOR_ALL(i, 0, n_rows, {
        array.stride(i) = n_cols;
    });
}
} // namespace


class DDynamicRaggedRightArrayKokkosTest : public ::testing::Test {
protected:
    size_t dim1, dim2;
    void SetUp() override {
        // Common setup code for all tests
        dim1 = 4;  // number of rows
        dim2 = 4;  // maximum number of columns per row
    }

    void TearDown() override {
        // Common cleanup code for all tests
    }
};

TEST_F(DDynamicRaggedRightArrayKokkosTest, Constructor) {
    DDynamicRaggedRightArrayKokkos<double> array(dim1, dim2, "test_array");

    EXPECT_EQ(array.dim1(), dim1);
    EXPECT_EQ(array.dim2(), dim2);
}

TEST_F(DDynamicRaggedRightArrayKokkosTest, StrideManagement) {
    DDynamicRaggedRightArrayKokkos<double> array(dim1, dim2, "test_array");

    for (size_t i = 0; i < dim1; i++) {
        EXPECT_EQ(array.stride_host(i), 0);
    }
}

TEST_F(DDynamicRaggedRightArrayKokkosTest, ValueAccess) {
    DDynamicRaggedRightArrayKokkos<double> array(dim1, dim2, "test_array");

    set_all_strides(array, dim1, dim2);

    // Write via host member, then verify on host
    array.host(0, 0) = 1.0;
    array.host(0, 1) = 2.0;
    array.host(1, 0) = 3.0;
    array.host(2, 0) = 4.0;
    array.host(2, 1) = 5.0;
    array.host(3, 0) = 6.0;

    EXPECT_DOUBLE_EQ(array.host(0, 0), 1.0);
    EXPECT_DOUBLE_EQ(array.host(0, 1), 2.0);
    EXPECT_DOUBLE_EQ(array.host(1, 0), 3.0);
    EXPECT_DOUBLE_EQ(array.host(2, 0), 4.0);
    EXPECT_DOUBLE_EQ(array.host(2, 1), 5.0);
    EXPECT_DOUBLE_EQ(array.host(3, 0), 6.0);
}

TEST_F(DDynamicRaggedRightArrayKokkosTest, SetValues) {
    DDynamicRaggedRightArrayKokkos<double> array(dim1, dim2, "test_array");

    set_all_strides(array, dim1, dim2);

    array.set_values(1.0);
    array.update_host();

    EXPECT_DOUBLE_EQ(array.host(0, 0), 1.0);
    EXPECT_DOUBLE_EQ(array.host(0, 1), 1.0);
    EXPECT_DOUBLE_EQ(array.host(1, 0), 1.0);
    EXPECT_DOUBLE_EQ(array.host(2, 0), 1.0);
    EXPECT_DOUBLE_EQ(array.host(2, 1), 1.0);
    EXPECT_DOUBLE_EQ(array.host(3, 0), 1.0);
}

TEST_F(DDynamicRaggedRightArrayKokkosTest, SetValuesSparse) {
    DDynamicRaggedRightArrayKokkos<double> array(dim1, dim2, "test_array");

    set_all_strides(array, dim1, dim2);

    array.set_values_sparse(1.0);
    array.update_host();

    EXPECT_DOUBLE_EQ(array.host(0, 0), 1.0);
    EXPECT_DOUBLE_EQ(array.host(0, 1), 1.0);
    EXPECT_DOUBLE_EQ(array.host(1, 0), 1.0);
    EXPECT_DOUBLE_EQ(array.host(2, 0), 1.0);
    EXPECT_DOUBLE_EQ(array.host(2, 1), 1.0);
    EXPECT_DOUBLE_EQ(array.host(3, 0), 1.0);
}

TEST_F(DDynamicRaggedRightArrayKokkosTest, UpdateFunctions) {
    DDynamicRaggedRightArrayKokkos<double> array(dim1, dim2, "test_array");

    set_all_strides(array, dim1, dim2);

    // Write via host, push to device, pull back and verify
    array.host(0, 0) = 1.0;
    array.host(0, 1) = 2.0;
    array.host(1, 0) = 3.0;
    array.host(2, 0) = 4.0;
    array.host(2, 1) = 5.0;
    array.host(3, 0) = 6.0;

    array.update_device();
    array.update_strides_host();
    array.update_strides_device();
    array.update_host();

    EXPECT_DOUBLE_EQ(array.host(0, 0), 1.0);
    EXPECT_DOUBLE_EQ(array.host(0, 1), 2.0);
    EXPECT_DOUBLE_EQ(array.host(1, 0), 3.0);
    EXPECT_DOUBLE_EQ(array.host(2, 0), 4.0);
    EXPECT_DOUBLE_EQ(array.host(2, 1), 5.0);
    EXPECT_DOUBLE_EQ(array.host(3, 0), 6.0);
}

TEST_F(DDynamicRaggedRightArrayKokkosTest, NameManagement) {
    DDynamicRaggedRightArrayKokkos<double> array(dim1, dim2, "test_array");

    set_all_strides(array, dim1, dim2);

    EXPECT_EQ(array.get_name(), "test_array");
}

TEST_F(DDynamicRaggedRightArrayKokkosTest, KokkosViewAccess) {
    DDynamicRaggedRightArrayKokkos<double> array(dim1, dim2, "test_array");

    set_all_strides(array, dim1, dim2);

    array.host(0, 0) = 1.0;
    array.host(0, 1) = 2.0;
    array.host(1, 0) = 3.0;
    array.host(2, 0) = 4.0;
    array.host(2, 1) = 5.0;
    array.host(3, 0) = 6.0;

    auto view = array.get_kokkos_dual_view();

    EXPECT_NE(view.h_view.data(), nullptr);
}
